### ISSUE TITLE
Using Florin Character ƒ

### ISSUE THREAD

**Issue by JirkaDellOro** [electron/electron-packager#1039]
We are using the ƒ frequently as a shortcut to our library in TypeScript as in
```typescript
import ƒ = OurLibraryWithReallyLongName;
```
which simply compiles to 
```javascript
    var ƒ = OurLibraryWithReallyLongName;
```

Works without issues in the browser and as electron build, but when building an executable with electron-packager, the complete line is gone!

Is there a way to fix this?

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by JirkaDellOro** [comment]
Thanks for getting back. I started to create a minimal project for demonstration, but I can't reproduce the bug. I'll reopen if it appears again.
