### ISSUE TITLE
WARNING: Found 'electron' but not as a devDependency, pruning anyway

### ISSUE THREAD

**Issue by quantrpeter** [electron/electron-packager#1073]
![bug](https://user-images.githubusercontent.com/50471577/68792784-0d32b500-0687-11ea-8de6-3f667f85d3a8.jpg)

**Comment by malept** [comment]
Your dependency `electron-tray-window` has a [dependency on `electron`](https://github.com/sfatihk/electron-tray-window/blob/afe125a0cf74dcd161b275544250e8c58a6f995b/package.json#L28-L30). It should only be in [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies), if you want to avoid the warning.

**Comment by quantrpeter** [comment]
thanks

**Comment by quantrpeter** [comment]
Oh, the warning message disappear, but the packed exe can't run, it said it can't find electron-tray-window. Any hints?

**Comment by malept** [comment]
How did you resolve the issue? By moving `electron-tray-window` to `devDependencies`? Because that will cause `electron-tray-window` to be pruned, since `devDependencies` are generally not necessary for apps in production. As I mentioned earlier, the solution is to have the `electron-tray-window` module fix its `package.json`.

The warning is just a warning, not an error.

**Comment by quantrpeter** [comment]
Thanks Mr Malept. Let me contact electron-tray-window author.
