### ISSUE TITLE
Rename electron.exe to ... Error

### ISSUE THREAD

**Issue by NeuronButter** [electron/electron-packager#1123]
Sorry, but I have no idea what is going on here. I've typed in this command: 
`electron-packager . spotify-overlay --all`
and this is the error that appears:
```
Official Linux/ia32 support is deprecated.
For more info: https://electronjs.org/blog/linux-32bit-support
Packaging app for platform win32 x64 using electron v8.0.0
ENOENT: no such file or directory, rename 'C:\Users\NEERON~1\AppData\Local\Temp\electron-packager\win32-x64\spotify-overlay-win32-x64\electron.exe' -> 'C:\Users\NEERON~1\AppData\Local\Temp\electron-packager\win32-x64\spotify-overlay-win32-x64\spotify-overlay.exe'
```
This is probably a no-brainer to what I'm doing wrong here, can someone please help me out? (also accidentally did bug, should be the 'help wanted' label. sorry)
Thanks!

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by malept** [comment]
Although this sounds like #1120 .
