### ISSUE TITLE
If the output is a subdirectory of a ignored directory the created exe errors out

### ISSUE THREAD

**Issue by SReject** [electron/electron-packager#1126]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 12.2.0
* **Electron Version:**
  * v7.1.9
* **Operating System:**
  * Win 10, x64, (10.0.18362)

### Expected Behavior
When the specified output directory is a sub-directory of a directory that has been ignored, the output executable should run without issue

### Actual Behavior
The created executable raises an error

### To Reproduce
* Create a minimal electron app
* Run the following `npx electron-packager . Name --out="./dist/pack" --platform=win32 --arch=x64 --ignore=/dist`

**Comment by malept** [comment]
I can't reproduce this on Windows 10/x64:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npx --no-install --ignore-existing electron-packager . --out=./dist/pack --ignore=/dist
```

FYI, by default the `--out` directory is always ignored.

In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by SReject** [comment]
Im not going to requst it reopened. I haven't been able to create a simplified way to reproduce the issues we were having
