### ISSUE TITLE
files that contain ".bac" are not packaged.

### ISSUE THREAD

**Issue by karniemi** [electron/electron-packager#1128]
### Preflight Checklist

* [x ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details
We just hit an issue that one of our files, namely main.<hash>.js,  had "bac" at beginning of the hash. electron-packager ignored the file, and did not include it in the package. Devastating to find out why that might happen. We are not setting any ignore rules for ".bac" ourself, and the files do get packaged if the hash does not contain ".bac".

* **Electron Packager Version:**
  * 14.1.1
* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior
should include file in package no matter what the hash-code is.

### Actual Behavior
did not include file in package, probably because the hash code matched some default ignore rule.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by karniemi** [comment]
@malept Thanks! Now having read the code for ignore and junk parameters, as well as the junk module, I agree that I might have followed a red herring. I'll have to dig in using your debug hints later on when back in the office. Let's close this ticket for now, as it will take quite some time. Sorry for the trouble!
