### ISSUE TITLE
app crashed in mac 

### ISSUE THREAD

**Issue by saurabhimedia** [electron/electron-packager#1142]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**14.2.1
  * 
* **Electron Version:**8.2.2
  * 
* **Operating System:**
  * 
* **Last Known Working Electron Packager version:**:
  * 

### Additional Information

The windows package runs fine in windows.The mac package is built in windows machine

**Comment by saurabhimedia** [comment]
Sorry to open it as a bug.

Actually I needed help on the above issue

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
