### ISSUE TITLE
packager does fine for linux - but win 32/64 not the same result

### ISSUE THREAD

**Issue by JerryGeis** [electron/electron-packager#1145]
I have nodejs 14.0.0  on centos 7. Wine 4.0.3
running npm build for linux works just fine.

 "scripts": {
    "start": "electron .",
    "build":     "electron-packager ./ --platform=linux --arch=x64      --overwrite",
    "build-win": "electron-packager ./ --platform=win32 --arch=ia32,x64 --overwrite"
  },

But running "npm run build-win" "seems" to work - but when I "copy" the whole directory over to my windows box and run the exe - it opens up a "dialog" window in stead of just showing the webpage I told it dispay. All my app does at this point if startup and display a web page. This works fine on linux.  I do get a blank - black kiosk page - but then the windows dialog pops up instead of just showing the webpage.

Is there something I am missing for the Win builds? 
Thanks,

Jerry

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.
