### ISSUE TITLE
can not package electron app

### ISSUE THREAD

**Issue by kerojiang** [electron/electron-packager#1160]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * Electron Packager 14.2.1
    Node v13.8.0
    Host Operating system: win32 10.0.18363 (x64)
* **Electron Version:**
  * 9.0.3
* **Operating System:**
  *  Windows 10 (18363)
* **Last Known Working Electron Packager version:**:
  *  no

### Expected Behavior
package the app to exe application

### Actual Behavior
package error
the cmd code:
electron-packager ./

the error message:
Packaging app for platform win32 x64 using electron v9.0.3
ENOENT: no such file or directory, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\electrion-test-win32-x64\electron.exe'  -> 
'C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\electrion-test-win32-x64\electrion-test.exe'

just run the project is ok with the cmd: npm run start

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.
