### ISSUE TITLE
obtengo errores en el codigo

### ISSUE THREAD

**Issue by jbello94** [electron/electron-packager#1165]
cuando ejecuto 
`electron-packager . LoginAndAdmin --overwrite --asar --platform=win32 --arch=ia32 --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Electron AutoService\"`
no obtengo el mismo resultado que mientras hago
`electron .`
Obtengo errores en el codigo, el error es 
`Uncaught SyntaxError: Unexpected identifier`

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
