### ISSUE TITLE
Support Yarn V2 PnP

### ISSUE THREAD

**Issue by Milo123459** [electron/electron-packager#1195]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Proposed Solution

Support Yarn v2 PnP
### Alternatives Considered

There are no alternatives, just maybe check is .pnp.js exists, if it does run X Y Z for building instead of copying node_modules
### Additional Information

N/A

**Comment by malept** [comment]
The last time I looked at this, it would need to export your dependencies to `node_modules` because Electron itself has no concept of Yarn's PnP feature.

That being said, this isn't a high priority for me to implement (without being [sponsored](https://github.com/sponsors/malept)). I'll gladly review a proposal to add this feature, although as far as I'm aware, there's nothing particular about this that requires it to be in Electron Packager itself, it could be a plugin that utilizes an [`afterCopy` hook](https://electron.github.io/electron-packager/v15.2.0/interfaces/electronpackager.options.html#aftercopy).

**Comment by Milo123459** [comment]
I get that, just might be cool as a lot of projects are switching to yarn v2
