### ISSUE TITLE
electron-packager throws the following warning - WARNING: The platform/arch combination darwin/arm64 is not currently supported by Electron Packager

### ISSUE THREAD

**Issue by MajuMadhusudanan** [electron/electron-packager#1200]
Hi,

I want to add Apple Silicon support for an app which is built using electron framework. But when i try to package the app using electron-packager, i'm getting the following warning on the terminal.

WARNING: The platform/arch combination darwin/arm64 is not currently supported by Electron Packager

I'm passing the following arguments --platform=darwin --arch=arm64 while running electron-packager. But it throws a warning.

How do i solve this issue? I want to create both darwin-x64 and darwin-arm64 app.

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by MajuMadhusudanan** [comment]
This is working now. I have upgraded packger (global one) to 15.2.0 and its working now
