### ISSUE TITLE
App(exe) não abre

### ISSUE THREAD

**Issue by cristyz** [electron/electron-packager#1215]
Meu app feito pelo electon-packager não abre, ele cria a pasta com o executável e etc, porém quando clico para executar/abrir o app.exe simplesmente não acontece nada...

Isso aconteceu com mais alguém? Vejo os tutorias em todos os cantos e deles todos abrem o app quando executado, porém o meu não acontece nada..

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.
