### ISSUE TITLE
EPERM: operation not permitted, mkdir 'C:\' Error shown when packaging

### ISSUE THREAD

**Issue by FrankPujo** [electron/electron-packager#1222]
### Preflight Checklist

* [ ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 1.9
* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Windows 10

### Expected Behavior
It is the first time using the packager, but the expected behavior should be the .exe file or a folder with the .exe and .dll files, if I'm not wrong.

### Actual Behavior
I receive the following output:  
_Packaging app for platform win32 x64 using electron v11.2.3_  
followed after a few seconds by:  
_EPERM: operation not permitted, mkdir 'C:\'_

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Can you use a newer version of Electron Packager? 1.9 is extremely out of date.

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by FrankPujo** [comment]
I came back today and it worked fine... not sure why thoguh!  
Anyway for anyone with a similiar problem in the future I reinstalled nodejs from the official website, then run `npm uninstall` and `npm install -g` (not 100% sure about this last one). Also run `npm cache clear` and reinstalled globally (adding `-g`) the packager to make sure it was installed correctly. After a restart it worked so maybe one of these things did the job.
