### ISSUE TITLE
command terminal hangs  while running electron packager command to bundle the code

### ISSUE THREAD

**Issue by Chandru22714** [electron/electron-packager#1241]
When i run the command **electron-packager . --overwrite --platform=win32,linux --arch=x64 --ignore=/e2e --ignore=/src --ignore=/projects --ignore=/offline --ignore=/.vscode --ignore=/node_modules --ignore=/local** , the command terminal hangs and showing like the screenshot, Node version: 12.18.2 and Electron packager: 15.2.0
![image](https://user-images.githubusercontent.com/15182262/118440212-f0a48c80-b704-11eb-9579-18870e39e834.png)

In my office, for others it is working perfectly fine, Only I am facing this issue. Please find the versions in the screenshot.

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should consider using one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron), as there are more people there available to answer questions.
