### ISSUE TITLE
the issue on electron run package with c++ dll file。

### ISSUE THREAD

**Issue by rodchen-king** [electron/electron-packager#1250]
### Issue Details
 
![image](https://user-images.githubusercontent.com/19780441/122340838-5b9bea00-cf75-11eb-87c0-e2076f6c4aa5.png)

In my project, invoke c++ dll file in the folder named ‘dll’, it worked fine on dev enviroument. when i electron package the project and then lunch it. 

### Expected Behavior
it will lunch successfully with no error.

### Actual Behavior
<![image](https://user-images.githubusercontent.com/19780441/122341092-acabde00-cf75-11eb-8e76-d8e2770aa41e.png)

**Comment by malept** [comment]
Either:

* Don't use asar, or
* use `asar.unpack` on DLL files

Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot continue to help debug your app at this time. If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
