### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception: Error: Cannot find module '/media/sf_linux-desktop/vue-electron-linux-x64/resources/app/background.js'

### ISSUE THREAD

**Issue by haha861924** [electron/electron-packager#1255]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.2.0
* **Electron Version:**
  * 11.0.0
* **Operating System:**
  *  Ubuntu x64 
* **Last Known Working Electron Packager version:**:
  * 15.2.0

### Actual Behavior
linux and windows app can  execute
### To Reproduce
`"build_linux": "electron-packager . test --platform=linux --arch=x64",`

### Additional Information
my windows app can work , but my linux app get error 

![image](https://user-images.githubusercontent.com/40877568/124237195-d81ff280-db49-11eb-9eb6-94510bbcae12.png)

and my folder is actually has this file 

![image](https://user-images.githubusercontent.com/40877568/124237284-f128a380-db49-11eb-9c54-5028564b4746.png)

how can I fix this error ?

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

Additionally, files and folders shared from Windows (via VirtualBox or Samba) tend to have unexpected behavior since you're sharing from a filesystem with a fundamentally different idea of permissions.
